# accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    ROLE_CHOICES = [
        ('user', 'User'),
        ('admin', 'Admin'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    cin = models.CharField(max_length=20, null=True, blank=True)
    birthdate = models.DateField(null=True, blank=True)
    photo = models.ImageField(upload_to='', blank=True, null=True)  # Changé de 'profile_photos/' à '' pour éviter la duplication
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='user')
    
    # New fields for AI bio
    bio = models.TextField(blank=True, null=True, help_text='Profile bio')
    art_style = models.CharField(max_length=200, blank=True, null=True, help_text='Artistic style (e.g., abstract, realistic, digital...)')
    art_interests = models.TextField(blank=True, null=True, help_text='Artistic interests and keywords')
    bio_generated = models.BooleanField(default=False, help_text='Bio was generated by AI')

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()
