# Clé unique de votre projet
sonar.projectKey=artygen
sonar.projectName=Artygen AI Art Platform

# Chemin des sources Python
sonar.sources=.
sonar.language=py

# Exclusions Django
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/static/**,**/media/**,**/*.html

# Configuration Python
sonar.python.version=3.8

# Rapports existants
sonar.python.pylint.reportPaths=pylint_report.txt

sonar.host.url=http://localhost:9000
