# Generated by Django 5.1.1 on 2025-10-27 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('profile', 'Photo de profil'), ('artwork', 'Artwork'), ('post', 'Post de blog'), ('event', "Image d'événement")], max_length=20)),
                ('status', models.CharField(choices=[('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('review', 'En révision')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('severity', models.CharField(max_length=20)),
                ('detected_issues', models.JSONField(default=list)),
                ('ai_reason', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de modération',
                'verbose_name_plural': 'Logs de modération',
                'ordering': ['-created_at'],
            },
        ),
    ]
