# Generated by Django 5.1.1 on 2025-10-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_moderationlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModerationLog',
        ),
    ]
