# Generated by Django 5.1.1 on 2025-10-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_moderationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='art_interests',
            field=models.TextField(blank=True, help_text='Intérêts artistiques et mots-clés', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='art_style',
            field=models.CharField(blank=True, help_text='Style artistique (ex: abstrait, réaliste, digital...)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Bio de profil', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio_generated',
            field=models.BooleanField(default=False, help_text='La bio a été générée par IA'),
        ),
    ]
