# Generated by Django 5.1.1 on 2025-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='art_interests',
            field=models.TextField(blank=True, help_text='Artistic interests and keywords', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='art_style',
            field=models.CharField(blank=True, help_text='Artistic style (e.g., abstract, realistic, digital...)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Profile bio', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio_generated',
            field=models.BooleanField(default=False, help_text='Bio was generated by AI'),
        ),
    ]
